-- =============================================================================
-- Ticket Analyzer — schema bootstrap
-- -----------------------------------------------------------------------------
-- Mirrors the `Ticket` ORM in `backend/app/models.py` (which itself mirrors
-- IMPLEMENTATION_PLAN.md §4). Run this against a fresh `ticket_db` to get
-- the same shape the FastAPI app would create via
--     Base.metadata.create_all(bind=engine)
-- on first boot.
--
-- The backend app does NOT depend on this file — the lifespan hook in
-- `backend/app/main.py` already calls `create_all` at startup. This file
-- exists for:
--   1. Onboarding reviewers who want to inspect the schema without booting
--      the stack.
--   2. Hand-seeding a production-ish DB where you don't want Python to own
--      the schema (e.g., a managed Postgres you provisioned separately).
--   3. Re-syncing the schema into a second environment.
--
-- Idempotent: safe to run multiple times (uses IF NOT EXISTS).
-- =============================================================================

BEGIN;

-- ---------------------------------------------------------------------------
-- Table: tickets
-- ---------------------------------------------------------------------------
-- One row per analyzed support ticket.
--
--   id          : surrogate PK, assigned by the `tickets_id_seq` sequence.
--   title       : short human label from the submitter. Required.
--   message     : free-form body that the sentiment model actually scores.
--   category    : optional routing tag. Nullable per PRD §4.
--   sentiment   : model output label, always "POSITIVE" or "NEGATIVE".
--   confidence  : model softmax score in [0.0, 1.0].
--   created_at  : server-assigned timestamp (DEFAULT now()).
--
-- The `created_at DESC` index supports the GET /tickets recency sort.
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.tickets (
    id          INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR(255)  NOT NULL,
    message     TEXT          NOT NULL,
    category    VARCHAR(100),
    sentiment   VARCHAR(20)   NOT NULL,
    confidence  DOUBLE PRECISION NOT NULL,
    created_at  TIMESTAMP     NOT NULL DEFAULT now()
);

-- Recency index for GET /tickets ORDER BY created_at DESC, id DESC.
-- (Matches the `Index("ix_tickets_created_at_desc", created_at.desc())` in
--  backend/app/models.py.)
CREATE INDEX IF NOT EXISTS ix_tickets_created_at_desc
    ON public.tickets (created_at DESC);

-- ---------------------------------------------------------------------------
-- CHECK constraints (defense-in-depth — also enforced by Pydantic).
-- Commented out by default to stay a 1:1 mirror of `models.py`. Uncomment
-- if you want the DB to reject bad rows even if validation is bypassed.
-- ---------------------------------------------------------------------------
--
-- ALTER TABLE public.tickets
--     ADD CONSTRAINT ck_tickets_sentiment_chk
--     CHECK (sentiment IN ('POSITIVE', 'NEGATIVE'));
--
-- ALTER TABLE public.tickets
--     ADD CONSTRAINT ck_tickets_confidence_range
--     CHECK (confidence >= 0.0 AND confidence <= 1.0);

COMMIT;

-- =============================================================================
-- Verification queries (run after applying the file):
--   \d public.tickets
--   SELECT count(*) FROM public.tickets;
-- =============================================================================
